name: kaggle_ml
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - asttokens==3.0.1
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - cmake==3.25.0
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - executing==2.2.1
      - filelock==3.19.1
      - fsspec==2025.9.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.4
      - ipykernel==7.1.0
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - lightgbm==4.6.0
      - lit==15.0.7
      - markdown==3.10
      - markupsafe==2.1.5
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.5
      - numpy==2.3.5
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - protobuf==6.33.1
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - requests==2.28.1
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - setuptools==68.2.2
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==1.26.13
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - xgboost==3.1.1
